version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      - redis
    volumes:
      - ../backend:/app
      - /app/__pycache__

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: celery -A app.core.celery_app worker --loglevel=info
    depends_on:
      - redis
